### ISSUE TITLE
Icons change size

### ISSUE THREAD

**Issue by torakiti2017** [MidoriKami/KitchenSync#2]
Icons changed in "KitchenSync" are smaller than the default size.

KitchenSync
<img width="85" alt="KitchenSync" src="https://user-images.githubusercontent.com/86459831/211142890-8dae027c-172f-471a-895c-97a630174069.png">

Default
<img width="92" alt="default" src="https://user-images.githubusercontent.com/86459831/211142909-14122b7e-c122-4824-803c-96138835080a.png">

Comparison
<img width="53" alt="比較" src="https://user-images.githubusercontent.com/86459831/211142927-8cc4c0a9-d467-41a4-b86d-a2aaa99c8097.png">

I recently installed this plugin and it helps to make the UI easier to understand. Thank you.

**Comment by MidoriKami** [comment]
KitchenSync does not modify icon sizes at all, ever. 

You're seeing the icon slot that is behind the icon and not seeing the edge of the actual icon.

This is an optical illusion.
